controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    tri_cont:
      type: tricycle_controller/TricycleController

tri_cont:
  publish_rate: 30
  base_frame_id: "base_link"
  odom_frame_id: "odom"
  wheel_radius: 0.1
  wheelbase: 0.3
  steering_joint: ""
  traction_joint_name: ""
  